### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Flatlinezor** [requtize/cropimg#1]
Hello!

Wonderfully simple, however I'd like to see a functionality, if it's not much of a problem to implement, I am sure many people would find it useful.

WOuld it be possible to have an overlay PNG fixed, just as the background png you have in the script?

So basically I'd want to have an overlay png, like a frame being on TOP of what the users crop, as transparent overlay. Imagine it as a watermark. 

I tried to replace the background png you have with the set output size of the cropper, and setting z index higher, but obviously it won't "bake" it over the uploaded pictures.

Any chance of implementing this?

Cheers,

David

**Comment by adambanaszkiewicz** [comment]
Hi,

This overlay should be moved with an image? Or stay in one position, example on center of cropping?
I wonder what You want do do with this overlay, what this overlay should give for user experience?
Can You describe what You want to this overlay should do?

PS. I'm sorry, but English is not my "default language" :)

**Comment by Flatlinezor** [comment]
Yes, exactly center of cropping. Basically my overlay watermark is 1210x440 in size, and that is what the users will crop the images to with it being top on it.
Thanks :) No worries about the english ;)

**Comment by Flatlinezor** [comment]
And imagine a constant watermark on top of what they crop in the viewport. Like your logo constantly there, BUT the reason to do it like this is for them to be able to position the picture they want to crop the way it looks good around the watermark. Simply :) Let me show you a pic in a second

**Comment by adambanaszkiewicz** [comment]
You can use onInit method. When plugin is initiated, append to DOM element (which element of plugin You want) Yours Image. If You want, You can wrap this image in DIV element, and style itwith CSS, so image would be resized when user will have smaller screen than You overlay Image.

I hope this would be helped.

**Comment by Flatlinezor** [comment]
https://dl.dropboxusercontent.com/u/78706473/overlay.jpg

Check this. So basically the grey area would stay constantly there, with 1.0 opacity, so the users know what part of the pic will be covered, so they position the crop accordingly. The implementation would need a PNG to be able to put fixed/centered to the output size set in the cropper, and that's it. :)

Would the method you mentioned now actually "save" the overlay into the picture? Because the outcome would have the overlay "baked" onto the cropped image, just as in the viewport?

**Comment by adambanaszkiewicz** [comment]
Ok, i understand. What about responsive? What about position of this element? There is so many options to configure this element.

Can You try do, what i describe earlier and, if this won't be good, then we try to solve this problem in other way.

**Comment by Flatlinezor** [comment]
The position is not an issue, because the size will be set all the time. Responsiveness is a fair point, but for now I just want to take babysteps as learning.

I'll try to do it, my only problem is that I am pretty much novice for now, just learning everything. If you could quickly just implement it as a no responsive, centered/centered size, so I can fool around with it, would be appreciated.

If you don't have time, no problem, I understand :)

**Comment by adambanaszkiewicz** [comment]
Nowadays, this plugin is only to preview an image, how it will look after cropping. Plugin not crop this image, and do not save image as file. You have to use some script (eg. in PHP) to crop image. Plugin provide an positions of cropped area, and dimensions of this area, and You can send this values on POST or AJAX to this script. And now, this stript do everything with this image, crops, add watermarks (even what You want to do, if You write this in Your script), and save a result file.

**Comment by adambanaszkiewicz** [comment]
OK, i prepare some example code which i describe abowe, but i have time only by evening.

**Comment by Flatlinezor** [comment]
Absolutely no problem, take your time and thanks for looking into it, appreciated!

**Comment by adambanaszkiewicz** [comment]
Here's fiddle: http://jsfiddle.net/qk2fdbqh/1/

So, You can replace an append method content what you want, in your case an image. But You must remember to style it if this image have to be abowe cropped image.

I hope it help.

**Comment by Flatlinezor** [comment]
It seems good, yes :)

**Comment by Flatlinezor** [comment]
Once again, thanks for the helps :)

I did everything I wanted, my only question is that is there a way to not have the awkward effect when clicking in to move the picture, since there is an additional layer onInit on the pic, in order to move the pic clicking the hover container area, it is like moving a pic for a second (at least in chrome), then the pic gets attached to the pointer. WIthout the png overlay added, it works beautifully, but with it, it is a bit strange usage wise.

So basically, if there is the overlay png as you sent in the fiddle, is there a way to completely disable it from user interactivity, so the click/drag becomes as smooth as it was, instead of first getting an image dragging "can't do" rectangle for the png layer?

I hope you understand, here is a link for what I wish not to have: https://dl.dropboxusercontent.com/u/78706473/grabmove.jpg

There is a circle crossed pointer error in the middle of the rectangle, which is not visible on the screenshot, since pointers are not registered by windows print screen. If I let go trying to grab the image, it gets attached to the moise and moves as it should, only the start of the click/grab is funny like this, because first it wants to "move" the fixed png overlay.

**Comment by adambanaszkiewicz** [comment]
I try to understand what you mean, I hope this is what you want to expect: http://jsfiddle.net/qk2fdbqh/3/

**Comment by Flatlinezor** [comment]
Exactly :) Thanks mate!

**Comment by Aufuray** [comment]
Hello, great plugin.
Do you have a working code on how to crop the image server-side?
