### ISSUE TITLE
Resetting the cropimg object

### ISSUE THREAD

**Issue by bradmurray** [requtize/cropimg#11]
I need a way to reset or change the object. Right now if I call .cropimg() on the image that already had it called it instantiates a new cropper inside of the old one instead of starting over.

**Comment by adambanaszkiewicz** [comment]
I'm working on it. Please be patient, I'm release new version of plugin soon.

**Comment by bradmurray** [comment]
For now what I do is set the .html property of the parent <div> back to just the raw image tag. Then I call .cropimg with the new settings.

**Comment by adambanaszkiewicz** [comment]
Plugin was upadated. Please read (section Reset): http://requtize.github.io/cropimg/documentation.html#doc-reset
