### ISSUE TITLE
image source change dynamically

### ISSUE THREAD

**Issue by BaddyBy** [requtize/cropimg#2]
Hi, thanks for simple and great component. But I have to change images dynamically. When image source is static, everything is fine. If I change source of image, like $("#cropimg").attr("src", "/Picture/GetImage/1"); it works strange. Some buttons do not work at all. Can you help me?

**Comment by adambanaszkiewicz** [comment]
Hi, there is way to fix that but i must write this function into plugin. I think may help function like "reinit" - i mean, this will take dimensions of image again (before this, You change an SRC of image) and create plugin elements again so the new image should work well.

I think this is good idea so i think of it in future days and add this in new release. But, in this moment, i think the best way is remove all this container generated by plugin, append an image in its place and run plugin again but this time on the new image.

**Comment by BaddyBy** [comment]
Hi, thanks for fast response. Actually, I did that way, I mean remove container and add image again and run plugin again :). I saw, that your code does not have any suitable method. So the only solution is to destroy and create again. But if you'll get new release with "reinit", please, let me know. Thanks.

**Comment by adambanaszkiewicz** [comment]
I'm glad You to solve Your problem. If I don't forget, I'll let You know :)
