### ISSUE TITLE
Server side crop process

### ISSUE THREAD

**Issue by Aufuray** [requtize/cropimg#3]
Hello, great plugin.
Do you have a working code on how to crop and get the final image with server-side script?

**Comment by adambanaszkiewicz** [comment]
I usually use PhpThumb library: https://github.com/masterexploder/PHPThumb
Method named: crop($startX, $startY, $cropWidth, $cropHeight)

If you don't know how to pass values from plugin to this library, please write, i help you if i will be able to help You.

**Comment by Aufuray** [comment]
Hello Adam,I've downloaded the the PhpTHumb library.The docs instruct me to include a file "PhpTHumb.inc.php" but I can't find this file in the library.
Please can you send me the version of the PhpThumb Library you have?
Thank you.

**Comment by adambanaszkiewicz** [comment]
Hi, i read the doc and i see that is old doc. I have another version of this lib, different of the doc and from the repo. Even if i send you my version of this lib, you will not be able to use it without doc. Always current version of this lib and it's doc was on this URL: http://phpthumb.gxdlabs.com/ but in some reasons this link won't work.

**Comment by adambanaszkiewicz** [comment]
I have write some simple demo of cropping image in PHP (in version 0.2.1). Script named script.php have comments, that you should understand how it works.

If you have a problem, open next issue and describe it.
