### ISSUE TITLE
Zoom with mouse, change of X,Y,W,H accordingly

### ISSUE THREAD

**Issue by nssnl** [requtize/cropimg#4]
Thanks for the great work, script is exactly what I was looking for.

One remark: it seems like X,Y,W,H are not updated when zooming with the mouse. If you perform another action afterwards (like dragging the image), it is updated correctly, but not if zooming with the mouse is your last action.

**Comment by adambanaszkiewicz** [comment]
Thank you for this response. I've made update for plugin, and now should be work as expected.

**Comment by nssnl** [comment]
Great, thanks
