### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sjcotto** [requtize/cropimg#5]
Hi, Thanks for the plugin

How to use the x, y, w, h to get the result image?

I'm trying to do this 

```
onChange: function (w, h, x, y) {

                var imageObj = $("#cropimg")[0];
                var canvas = $("#preview")[0];
                var context = canvas.getContext("2d");

                context.drawImage(imageObj, x, y, w, h, 0, 0, canvas.width, canvas.height);

            }
```

but dosen't work correctly

**Comment by adambanaszkiewicz** [comment]
I try to solve this but i don't have idea why this work like this. I don't use canvas' in my programming so it's little difficult to solve this problem. 

I create [fiddle](http://jsfiddle.net/rm72vhxv/) with your code and there is really shocking effect when i move image in cropped area. In canvas, this image is sticky to x:y 0:0 and resize itself really not normal. I don't have idea why this work like this.

When plugin was created, i check it only to work with PHP library to crop image from results and that work perfectly. I don't know what to say. I will check this problem on the days and if i solve this, i notice it here.

**Comment by sjcotto** [comment]
Thanks

2015-02-28 17:15 GMT-02:00 Adam notifications@github.com:
