### ISSUE TITLE
Multiple Instances of cropimg in same page

### ISSUE THREAD

**Issue by lucianobosco** [requtize/cropimg#6]
Hi, this is a great plugin but wondering if there is a way to create more than 1 instance per page since it only applies to the latest added element dinamically. Make sense?
I'm trying to implement it on a media queue upload system but it's not working at all. With one element it works perfectly, but if a new one is added the action buttons (resize, zoom, etc) from the first image work over the latest added image.
Did someone figure out how to have more than 1 cropimg working correctly?

Thanks in advance.

**Comment by adambanaszkiewicz** [comment]
Hi, thanks for report this problem. I've already rewrite some code to make plugin instantiated multiple on page. Just download new release (0.2.0) and try it.

If You have problems with this new version, please report here.
