### ISSUE TITLE
Zoom speed

### ISSUE THREAD

**Issue by Noppey** [requtize/cropimg#8]
I know that the mouse zooming is configurable, but for now I only use the zoom buttons.
I had to increase the zoom-increment to 0.005 to speed it up to my taste.
It would be nice if this was configurable.

**Comment by adambanaszkiewicz** [comment]
Nice catch. I did not think of that. I add this to next, fix release. Thank You for Your report.

**Comment by adambanaszkiewicz** [comment]
I was add in version 0.2.1 option named zoomStep. It takes integer (or float) as parameter. 1 is a default zoom step. Higher value gives you faster zooming.
