### ISSUE TITLE
Get the cropped / resized Image

### ISSUE THREAD

**Issue by cweissbrandmarker** [requtize/cropimg#9]
Hi there - how can i get the cropped and resized image?! thanks!

**Comment by adambanaszkiewicz** [comment]
Plugin inserts values of cropped image (with, height, x and y) into inputs in HTML document. You have to create these inputs and set them ID's (see documentation). You can also get values, by set a callback for onChange() event function (see documentation). Now, if You have values, you can crop and resize image in PHP (submit a form default or using AJAX), or calculate a real-time preview image in Canvas or simple positioned IMG in overflowed DIV.

If you have more questions, feel free to write here.

**Comment by cweissbrandmarker** [comment]
Thanks for the quick answer! can you send me the code for the php script and maybe the real-time preview? ive tried it but i cant get it to work :-(

**Comment by cweissbrandmarker** [comment]
for php skript: i can save the image - just need the code for cropping / resizing

**Comment by adambanaszkiewicz** [comment]
In simple demo i add file named script.php that contains simple code to crop image from data delivered from plugin. Just download current version (0.2.1), move it to the server, call index.php file, change cropped image or zoom it and click button "Crop this image" to create live preview.
